[package]
name = "SKStatic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.25.0"  # 최신 버전 확인 후 사용
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
